"""Add structured analysis fields to JournalEntry

Revision ID: c75418c1a833
Revises: ff4d9851aab3
Create Date: 2025-07-14 14:47:39.235381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c75418c1a833'
down_revision: Union[str, None] = 'ff4d9851aab3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal_entries', sa.Column('emotional_landscape', sa.JSON(), nullable=True))
    op.add_column('journal_entries', sa.Column('themes_topics', sa.JSON(), nullable=True))
    op.add_column('journal_entries', sa.Column('cognitive_patterns', sa.JSON(), nullable=True))
    op.add_column('journal_entries', sa.Column('relational_dynamics', sa.JSON(), nullable=True))
    op.add_column('journal_entries', sa.Column('contextual_clues', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('journal_entries', 'contextual_clues')
    op.drop_column('journal_entries', 'relational_dynamics')
    op.drop_column('journal_entries', 'cognitive_patterns')
    op.drop_column('journal_entries', 'themes_topics')
    op.drop_column('journal_entries', 'emotional_landscape')
    # ### end Alembic commands ###
