version: "3.8"

services:
  backend:
    build:
      context: ./apps/backend
      dockerfile: src/api/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./apps/backend/src:/app/src
    environment:
      - DATABASE_URL=postgresql://youruser:yourpassword@db/yourdb
      - QDRANT_URL=http://qdrant:6333
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/%2F
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      - db
      - qdrant
      - rabbitmq
      - ollama

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: yourdb
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./apps/backend/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  db_data:
  qdrant_data:
  rabbitmq_data:
  ollama_data:
